export interface Textbook {
  id: string;
  title: string;
  titleEn: string;
  description: string;
  descriptionEn: string;
  priority: 1 | 2 | 3;
  icon: string;
  accentColor:
    | "amber"
    | "violet"
    | "teal"
    | "blue"
    | "sky"
    | "emerald"
    | "indigo"
    | "rose"
  | "fuchsia"
  | "orange"
  | "cyan";
  htmlFile?: string;
  htmlFileEn?: string;
  htmlFileKo?: string;
  sections: number;
  estimatedMinutes: number;
  tags: string[];
  ready: boolean;
}

export const TEXTBOOKS: Textbook[] = [
  {
    id: "cowork-mastery",
    title: "Cowork 실전 정복",
    titleEn: "Cowork Mastery",
    description: "Cowork, plugin, agent 흐름을 작업 단위로 설계하는 실전 교재입니다.",
    descriptionEn: "An operations-focused textbook that maps cowork, plugins, and agent workflows end to end.",
    priority: 1,
    icon: "cowork",
    accentColor: "amber",
    htmlFile: "cowork-learning.html",
    sections: 12,
    estimatedMinutes: 45,
    tags: ["Cowork", "Plugin", "Agent"],
    ready: true,
  },
  {
    id: "prompt-engineering",
    title: "프롬프트 엔지니어링 실전",
    titleEn: "Prompt Engineering in Practice",
    description: "Few-shot, 출력 구조화, 평가 기준을 실전 패턴으로 익히는 교재입니다.",
    descriptionEn: "Practice-ready coverage of few-shot prompting, structured outputs, and role design patterns.",
    priority: 1,
    icon: "prompt",
    accentColor: "violet",
    htmlFile: "prompt-engineering.html",
    htmlFileEn: "prompt-engineering-en.html",
    htmlFileKo: "prompt-engineering.html",
    sections: 10,
    estimatedMinutes: 40,
    tags: ["Prompt", "Few-shot", "Output"],
    ready: true,
  },
  {
    id: "claude-code-intro",
    title: "Claude Code 입문",
    titleEn: "Getting Started with Claude Code",
    description: "CLI 흐름, 파일 수정, 자동화 감각을 첫 실습부터 연결하는 교재입니다.",
    descriptionEn: "A first-step textbook covering CLI flow, file edits, and automation with Claude Code.",
    priority: 1,
    icon: "terminal",
    accentColor: "teal",
    htmlFile: "claude-code-intro.html",
    htmlFileEn: "claude-code-intro-en.html",
    htmlFileKo: "claude-code-intro.html",
    sections: 10,
    estimatedMinutes: 35,
    tags: ["Claude Code", "CLI", "Automation"],
    ready: true,
  },
  {
    id: "agent-patterns",
    title: "AI 에이전트 워크플로 패턴",
    titleEn: "AI Agent Workflow Patterns",
    description: "도구 호출, 병렬 실행, 메모리 전략을 패턴 중심으로 배우는 교재입니다.",
    descriptionEn: "Visual guides to tool calling, orchestration, memory, and practical agent workflow patterns.",
    priority: 2,
    icon: "agent",
    accentColor: "blue",
    htmlFile: "agent-patterns.html",
    sections: 10,
    estimatedMinutes: 40,
    tags: ["Agent", "Workflow", "Multi-agent"],
    ready: true,
  },
  {
    id: "api-fundamentals",
    title: "API 기초와 연결",
    titleEn: "Claude API Fundamentals",
    description: "메시지 구조, 토큰, 스트리밍, 함수 호출을 압축해서 정리한 교재입니다.",
    descriptionEn: "A compact textbook on messages, tokens, streaming, and function/tool calling basics.",
    priority: 2,
    icon: "api",
    accentColor: "sky",
    htmlFile: "api-basics-learning.html",
    sections: 10,
    estimatedMinutes: 35,
    tags: ["API", "Function Calling", "Streaming"],
    ready: true,
  },
  {
    id: "data-analysis-ai",
    title: "데이터 분석 with AI",
    titleEn: "Data Analysis with AI",
    description: "CSV를 읽고 요약하고 보고서로 바꾸는 흐름을 따라가는 교재입니다.",
    descriptionEn: "Use AI to inspect CSVs, summarize findings, and turn raw data into practical reports.",
    priority: 2,
    icon: "chart",
    accentColor: "emerald",
    htmlFile: "data-analysis-with-ai.html",
    sections: 8,
    estimatedMinutes: 30,
    tags: ["Data", "Excel", "Visualization"],
    ready: true,
  },
  {
    id: "github-part1-basics",
    title: "GitHub 입문 Part 1",
    titleEn: "GitHub Basics Part 1",
    description: "Git와 GitHub 차이, 저장소, commit, push 흐름을 처음부터 배우는 입문 교재입니다.",
    descriptionEn: "A beginner textbook covering Git vs GitHub, repositories, commits, and the first push workflow.",
    priority: 2,
    icon: "github",
    accentColor: "sky",
    htmlFile: "github-part1-basics.html",
    sections: 12,
    estimatedMinutes: 40,
    tags: ["GitHub", "Beginner", "Workflow"],
    ready: true,
  },
  {
    id: "github-part2-collaboration",
    title: "GitHub 협업 Part 2",
    titleEn: "GitHub Collaboration Part 2",
    description: "Pull Request, 충돌 해결, Actions, 오픈소스 기여를 다루는 협업 실전 교재입니다.",
    descriptionEn: "A practical collaboration textbook covering pull requests, conflict resolution, Actions, and open source flow.",
    priority: 2,
    icon: "github",
    accentColor: "indigo",
    htmlFile: "github-part2-collaboration.html",
    sections: 12,
    estimatedMinutes: 45,
    tags: ["GitHub", "Collaboration", "Pull Request"],
    ready: true,
  },
  {
    id: "copilot-claude-integration",
    title: "Copilot + Claude 통합",
    titleEn: "Copilot and Claude Integration",
    description: "여러 코딩 보조 도구를 팀 환경에서 함께 쓰는 방식을 다룹니다.",
    descriptionEn: "A workflow textbook for combining Copilot and Claude in collaborative engineering environments.",
    priority: 3,
    icon: "integration",
    accentColor: "indigo",
    htmlFile: "copilot-claude-learning.html",
    sections: 8,
    estimatedMinutes: 25,
    tags: ["Copilot", "Enterprise", "Workflow"],
    ready: true,
  },
  {
    id: "ai-security",
    title: "AI 보안과 안전 사용",
    titleEn: "AI Security and Safe Usage",
    description: "권한, 로그, 민감정보, 사내 문서 사용 시 주의점을 정리한 교재입니다.",
    descriptionEn: "Safety-first guidance for permissions, logging, sensitive data, and internal AI adoption.",
    priority: 3,
    icon: "shield",
    accentColor: "rose",
    htmlFile: "ai-security-learning.html",
    sections: 8,
    estimatedMinutes: 25,
    tags: ["Security", "Privacy", "Safety"],
    ready: true,
  },
  {
    id: "multimodal-ai",
    title: "멀티모달 AI 활용",
    titleEn: "Multimodal AI Applications",
    description: "이미지, PDF, 음성 입력이 실제 흐름에 어떻게 붙는지 보여주는 교재입니다.",
    descriptionEn: "Learn how images, PDFs, and voice inputs fit into multimodal AI workflows.",
    priority: 3,
    icon: "multimodal",
    accentColor: "fuchsia",
    htmlFile: "multimodal-ai-learning.html",
    sections: 8,
    estimatedMinutes: 25,
    tags: ["Vision", "PDF", "Voice"],
    ready: true,
  },
  {
    id: "ai-landscape",
    title: "AI 모델 비교 가이드",
    titleEn: "AI Landscape Comparison",
    description: "Claude, GPT, Gemini, Copilot의 차이를 선택 기준 중심으로 정리합니다.",
    descriptionEn: "Compare Claude, GPT, Gemini, and Copilot through decision criteria and real use cases.",
    priority: 3,
    icon: "compare",
    accentColor: "orange",
    htmlFile: "ai-model-comparison-learning.html",
    sections: 8,
    estimatedMinutes: 25,
    tags: ["Claude", "GPT", "Gemini", "Comparison"],
    ready: true,
  },
  {
    id: "mcp-learning",
    title: "MCP 프로토콜 인터랙티브 학습실",
    titleEn: "MCP Protocol Interactive Lab",
    description: "MCP 개념, 연결 구조, API 키 판단, CLI와 Web LLM 차이를 단계별로 이해합니다.",
    descriptionEn: "A step-by-step interactive textbook explaining MCP concepts, setup flow, API-key decisions, and client differences.",
    priority: 1,
    icon: "mcp",
    accentColor: "cyan",
    htmlFile: "mcp-learning.html",
    htmlFileEn: "mcp-learning-en.html",
    htmlFileKo: "mcp-learning.html",
    sections: 11,
    estimatedMinutes: 45,
    tags: ["MCP", "Protocol", "Connector"],
    ready: true,
  },
  {
    id: "marketplace-learning",
    title: "Marketplace 인터랙티브 학습실",
    titleEn: "Marketplace Interactive Lab",
    description: "Marketplace, Skill, Plugin, Cowork 흐름을 실제 사용 관점으로 묶어 설명합니다.",
    descriptionEn: "An interactive textbook for marketplace, skills, plugins, and cowork explained through guided personas.",
    priority: 1,
    icon: "marketplace",
    accentColor: "amber",
    htmlFile: "marketplace-learning.html",
    htmlFileEn: "marketplace-learning-en.html",
    htmlFileKo: "marketplace-learning.html",
    sections: 10,
    estimatedMinutes: 50,
    tags: ["Marketplace", "Skill", "Plugin", "Cowork"],
    ready: true,
  },
];

export const TEXTBOOK_PRIORITY_LABELS = {
  en: {
    1: "Start now",
    2: "Expand skills",
    3: "Trending",
  },
  ko: {
    1: "지금 학습",
    2: "실무 확장",
    3: "최신 흐름",
  },
} as const;
